name: "CD pipeline"

on:
    workflow_run:
        workflows: ["sample react ci pipeline / workflows"]
        types:
            - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

        steps:

            - name: "setup nodejs"
              uses: action/setup-node@v4
              with:
                    node-version: '21'
            
            - name: "setup vercel cli"
              run: npm install -g vercel  # corrected from versal to vercel

            - name: "download build files"
              uses: actions/download-artifact@v4
              with:
                name: build
                run-id: ${{ github.event.workflow_run.id }}  # fixed variable name
                github-token: ${{ github.token }}

            - name: "Deploy to vercel"
              run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm --name=cicdproject
